# Generated by Django 3.2 on 2021-04-30 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='progress.book'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='book_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='progress.bookprogress'),
        ),
    ]
