name: Python package

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
    - name: Lint
      run: |
        pipenv run flake8 . --count --show-source --statistics
        pipenv run isort . --check
    - name: Test with pytest
      run: |
        pipenv run pytest
